## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
rand_array = np.random.randint(-10, 10, size=(4, 4))
print(rand_array)

rand_array[(rand_array>3) & (rand_array<8)] *= -1
print(rand_array)

[[ -8  -7   4 -10]
 [-10 -10   4   1]
 [ -9   2  -3   4]
 [ -5  -4  -1  -4]]
[[ -8  -7  -4 -10]
 [-10 -10  -4   1]
 [ -9   2  -3  -4]
 [ -5  -4  -1  -4]]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
rand_array[(rand_array == rand_array.max())] = 0
print(rand_array)

[[ -8  -7  -4 -10]
 [-10 -10  -4   1]
 [ -9   0  -3  -4]
 [ -5  -4  -1  -4]]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
A = np.random.randint(1, 10, (2, 2))
B = np.random.randint(1, 10, (2, 2))
A1, B1 = np.meshgrid(A, B)
print(A, B)
C = np.stack([A1.ravel(), B1.ravel()], axis=1)
print(C)

[[7 6]
 [6 3]] [[1 1]
 [1 9]]
[[7 1]
 [6 1]
 [6 1]
 [3 1]
 [7 1]
 [6 1]
 [6 1]
 [3 1]
 [7 1]
 [6 1]
 [6 1]
 [3 1]
 [7 9]
 [6 9]
 [6 9]
 [3 9]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(1, 5, (8, 3))
B = np.random.randint(1, 5, (2, 2))

rows = np.where(np.all([np.isin(A, row).any(axis=1) for row in B], axis=0))
print(rows)
print(A)
print(B)

(array([1, 2, 4, 5, 6, 7]),)
[[1 2 1]
 [4 2 4]
 [4 4 3]
 [1 1 4]
 [2 2 4]
 [1 4 3]
 [2 4 3]
 [3 1 3]]
[[4 3]
 [3 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [16]:
A = np.random.randint(1, 3, (10,3))
unique = np.logical_and.reduce(A[:,1:] == A[:,:-1], axis=1)
res = A[~unique]
print(A)
print(res)

[[1 2 1]
 [2 2 1]
 [2 1 1]
 [1 2 1]
 [1 2 2]
 [1 1 1]
 [1 2 1]
 [2 1 1]
 [2 1 1]
 [1 1 1]]
[[1 2 1]
 [2 2 1]
 [2 1 1]
 [1 2 1]
 [1 2 2]
 [1 2 1]
 [2 1 1]
 [2 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
A = np.random.randint(1, 3, (4, 4))
print(np.unique(A, axis=0))

[[1 1 2 1]
 [2 1 1 1]
 [2 1 1 2]
 [2 2 2 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [14]:
#решение без numpy
res = 1
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
for i in range(len(X) - 1):
    if X[i][i] != 0:
        res *= X[i][i]
print(res)


#решение с numpy
Y = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(np.prod(np.diag(Y)[np.diag(Y) != 0]))

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
#решение без numpy
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(sorted(x) == sorted(y))

#решение с numpy
X = np.array([1, 2, 2, 4])
Y = np.array([4, 2, 1, 2]) 
print(np.bincount(X) == np.bincount(Y))

True
[ True  True  True  True  True]


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [11]:
#решение без numpy
res = 0
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
for i in range(len(x) - 1):
    if x[i] == 0:
        res = max(res, x[i + 1])
print(res)

#решение с numpy
X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
max_value = np.max(X[np.where(X[:-1] == 0)[0] + 1])
print(max_value)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
#решение без numpy
x = [2, 2, 2, 3, 3, 3, 5]
keys = {}
for i in x:
    if i in keys:
        keys[i] += 1
    else:
        keys[i] = 1
res = (list(keys.keys()),list(keys.values()))
print(res)

#решение с numpy
X = np.array([2, 2, 2, 3, 3, 3, 5]) 
values1, keys1 = np.unique(X, return_counts=True)
res1 = (values1, keys1)
print(res1)

([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [13]:
import time
from scipy.spatial.distance import cdist
#решение без numpy
import math
x = [[1, 2],[5, 8]]
y = [[5, 9], [8, 7]]
res = []
start_time = time.time()
for i in x:
    row=[]
    for j in y:
        distance = math.sqrt(sum((a - b) ** 2 for a, b in zip(i, j)))
        row.append(distance)
    res.append(row)
end_time = time.time()
print(res)
print(end_time - start_time)

#решение с numpy
X = np.array(x)
Y = np.array(y)
start_time = time.time()

diff = X[:, None] - Y[None, :]
distances = np.sqrt(np.sum(diff ** 2, axis =- 1))

end_time = time.time()
print(distances)
print(end_time - start_time)

start_time = time.time()
dist_matrix = cdist(X, Y)
end_time = time.time()
print(dist_matrix)
print(end_time - start_time)


[[8.06225774829855, 8.602325267042627], [1.0, 3.1622776601683795]]
0.0003409385681152344
[[8.06225775 8.60232527]
 [1.         3.16227766]]
0.0007390975952148438
[[8.06225775 8.60232527]
 [1.         3.16227766]]
0.000591278076171875


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [2]:
import numpy as np
from scipy.stats import percentileofscore

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [3]:
calorie_stats = np.loadtxt("/Users/BigTime/Downloads/Data/cereal.csv", delimiter = ",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [4]:
average_calories = np.mean(calorie_stats)
print('Разница в калориях:', average_calories - 60)

Разница в калориях: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [5]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [6]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [13]:
for i in calorie_stats_sorted:
    if i > 60:
        print(percentileofscore(calorie_stats, i))
nth_percentil = percentileofscore(calorie_stats, 60)
print('Наимениший процентиль, превышающий 60 ккал:', nth_percentil)

5.8441558441558445
5.8441558441558445
7.792207792207792
12.987012987012987
12.987012987012987
12.987012987012987
12.987012987012987
12.987012987012987
12.987012987012987
12.987012987012987
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
28.57142857142857
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
58.44155844155844
5

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [61]:
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats)
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [65]:
calorie_std = np.std(calorie_stats)
calorie_std
#мы не можем сделать обобщение, что в большинстве злаков содержится около 100 ккал, т.к. разброс в 20 калорий ощутим
#с этой информацией мы можем утверждать, что калорийность наших злаков значительно ниже.

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
В ходе анализа мы выявили, что в среднем калорийность такого типа продукта составляет 100+-20 ккалорий. Наши злаки 
обладают калорийностью ниже примерно на два стандартных отклонения, в связи с этим мы можем утверждать, что эти
цифры гораздо лучше чем у большинства конкурентов.